#!/bin/bash

########################
# Author: Abhijit Shenolikar
# Date: 21st December 2023
# version: v1
# This script will generate password which takes 2 arguments number of passwords and password length.
#######################
# Example:
#   Generate 3 passwords that are 8 characters long.
#   random-password-generator 3 10


echo "*************PASSWORD GENERATOR********************"

# 1st argument is Number of password you want to generate. Default number of passwords is one 
echo "NUMBER_OF_PASSWORDS=$1"
read NUMBER_OF_PASSWORDS
[ -n "$NUMBER_OF_PASSWORDS" ] || NUMBER_OF_PASSWORDS=1

# 2nd argument is length of password.The default and maximum length is 64 characters.
echo "PASSWORD_LENGTH=$2"
read PASSWORD_LENGTH
[ -n "$PASSWORD_LENGTH" ] || PASSWORD_LENGTH=64

for x in $(seq 1 $NUMBER_OF_PASSWORDS)
do
  openssl rand -base64 48 | cut -c1-${PASSWORD_LENGTH}
done
